package com.itax.billbuddies.models;

public class PurchaseItem {
    public String id;
    public String loginID;
    public String company_id;
    public String session_fin_year;
    public String due_date;
    public String bank_id;
    public String supplier_id;
    public String purchase_date;
    public String supplier_invoice_no;
    public String supplier_invoice_date;
    public String invoice_id;
    public String reference_no;
    public String invoice_discount_type = null;
    public String invoice_discount;
    public String invoice_discount_amount;
    public String shipping_charges;
    public String tax_amount;
    public String discount_amount;
    public String other_charges;
    public String roundoff;
    public String subtotal;
    public String total;
    public String status;
    public String paymentmethod;
    public String total_paid_amount;
    public String last_paid_amount_on = null;
    public String total_due_amount;
    public String extra_amount_received = null;
    public String notes;
    public String scan_supplier_bill = null;
    public String rcm_applicable;
    public String pan_card;
    public String tds_bill_applicable;
    public String tds_amount;
    public String date_created;
    public String updatedBy = null;
    public String date_modified = null;
}
